version: '2'
exclude_patterns:
  - 'config/'
  - '**/node_modules/'
  - '**/spec/'
  - '**/__mocks__/'
  - '**/__tests__/'
  - '**/*.spec.jsx'
  - '**/*.spec.js'
  - 'src/**/index.js'
  - 'src/serviceWorker.js'
  - 'src/redux/store.js'
